import os

AVTOCOD_TOKEN = os.getenv("AVTOCOD_TOKEN")
AVTOCOD_EMAIL = os.getenv("AVTOCOD_EMAIL")
AVTOCOD_PASSWORD = os.getenv("AVTOCOD_PASSWORD")

NOT_AUTHORIZED = not AVTOCOD_TOKEN or not (AVTOCOD_EMAIL and AVTOCOD_PASSWORD)
