name: Integration Tests

on:
  push:
    branches:
      - develop
      - develop-*
  pull_request:
    branches:
      - develop
      - develop-*
  workflow_dispatch:
  schedule:
    # once in a week
    - cron: '0 0 * * 0'


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        # run only the one worker to avoid to many requests to the API
        os:
          - ubuntu-latest
        python-version:
          - '3.8'

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ secrets.CACHE_VERSION }}


      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction


      - name: Run Tests (integration)
        continue-on-error: true
        run: |
          poetry run pytest -m "integration" 
